[versions]

kotlin = "1.9.0"
dokka = "1.8.20"
changeLog = "2.1.2"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
changeLog = { id = "org.jetbrains.changelog", version.ref = "changeLog" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
